"use client"

import React from "react"
import Link from "next/link"
import {
  ArrowLeft,
  BookOpen,
  Calendar,
  Clock,
  Download,
  FileText,
  Globe,
  Heart,
  Share2,
  Sparkles,
  Volume2,
  Square,
} from "lucide-react"
import { Navigation } from "@/components/navigation"
import { Footer } from "@/components/footer"
import { RatingStars } from "@/components/rating-stars"
import { ReviewForm } from "@/components/review-form"
import { AIResponseCard } from "@/components/ai-response-card"
import { ChatWindow } from "@/components/chat-window"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { AISidebar } from "@/components/ai/AISidebar"
import { useTextToSpeech } from "@/lib/useTextToSpeech"
import type { Book, Review } from "@/lib/mock-data"
import { supabase } from "@/lib/supabaseClient"
import { mapDbReview } from "@/lib/dataMappers"

interface Props {
  book: Book
  bookReviews: Review[]
}

export function BookDetailClient({ book, bookReviews }: Props) {
  const [isGeneratingSummary, setIsGeneratingSummary] = React.useState(false)
  const [summary, setSummary] = React.useState<string | null>(null)
  const [reviews, setReviews] = React.useState<Review[]>(bookReviews)
  const { speak, stop, allowed: ttsAllowed } = useTextToSpeech()

  const handleGenerateSummary = async () => {
    setIsGeneratingSummary(true)
    await new Promise((resolve) => setTimeout(resolve, 2000))
    setSummary(
      `This is an AI-generated summary of "${book.title}" by ${book.author}.\n\nKey Points:\n1. The book provides comprehensive coverage of ${book.category.toLowerCase()} topics relevant to Ethiopian context.\n2. Written in accessible ${book.language}, making it suitable for students and researchers alike.\n3. The author draws from extensive research and practical experience.\n4. Includes case studies and examples specific to Ethiopia.\n5. Recommended for advanced undergraduate and graduate students.\n\nThis summary was generated by AI and may not capture all nuances of the original text.`
    )
    setIsGeneratingSummary(false)
  }

  const handleSubmitReview = async (input: { rating: number; content: string }) => {
    const { rating, content } = input
    const { data, error } = await supabase
      .from("reviews")
      .insert({
        book_id: book.id,
        user_name: "Anonymous",
        rating,
        comment: content,
        sentiment: "positive",
      })
      .select("*")
      .single()

    if (!error && data) {
      const mapped = mapDbReview(data)
      setReviews((prev) => [mapped, ...prev])
    }
  }

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navigation />

      <main className="flex-1">
        {/* Back Button */}
        <div className="border-b border-border">
          <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
            <Button asChild variant="ghost" size="sm">
              <Link href="/books">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Library
              </Link>
            </Button>
          </div>
        </div>

        {/* Book Header */}
        <section className="border-b border-border bg-muted/30">
          <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
            <div className="flex flex-col gap-8 lg:flex-row">
              {/* Book Cover */}
              <div className="shrink-0">
                <div className="relative aspect-[3/4] w-full max-w-[240px] mx-auto lg:mx-0 overflow-hidden rounded-xl bg-muted shadow-lg">
                  <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-primary/20 to-secondary/20">
                    <BookOpen className="h-20 w-20 text-primary/40" />
                  </div>
                  {book.isAvailableOffline && (
                    <Badge
                      variant="secondary"
                      className="absolute right-3 top-3 gap-1"
                    >
                      <Download className="h-3 w-3" />
                      Offline
                    </Badge>
                  )}
                </div>
              </div>

              {/* Book Info */}
              <div className="flex-1">
                <Badge variant="outline" className="mb-3">
                  {book.category}
                </Badge>
                <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl text-balance">
                  {book.title}
                </h1>
                <p className="mt-2 text-lg text-muted-foreground">
                  by {book.author}
                </p>

                {/* Rating */}
                <div className="mt-4 flex items-center gap-4">
                  <RatingStars rating={book.rating} size="md" showValue />
                  <span className="text-muted-foreground">
                    ({book.reviewCount} reviews)
                  </span>
                </div>

                {/* Metadata */}
                <div className="mt-6 flex flex-wrap gap-4 text-sm text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <Globe className="h-4 w-4" />
                    {book.language}
                  </div>
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4" />
                    {book.pages} pages
                  </div>
                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4" />
                    {book.publishedYear}
                  </div>
                  <div className="flex items-center gap-2">
                    <Download className="h-4 w-4" />
                    {book.downloadCount.toLocaleString()} downloads
                  </div>
                </div>

                {/* Actions */}
                <div className="mt-8 flex flex-wrap gap-3 items-center">
                  <Button size="lg" className="gap-2">
                    <BookOpen className="h-5 w-5" />
                    Read Now
                  </Button>
                  {book.isAvailableOffline && (
                    <Button size="lg" variant="outline" className="gap-2">
                      <Download className="h-5 w-5" />
                      Download
                    </Button>
                  )}
                  <Button size="lg" variant="outline" className="gap-2">
                    <Heart className="h-5 w-5" />
                    Save
                  </Button>
                  <Button size="lg" variant="ghost" className="gap-2">
                    <Share2 className="h-5 w-5" />
                    Share
                  </Button>
                  <Button
                    size="lg"
                    variant="outline"
                    className="gap-2"
                    disabled={!ttsAllowed}
                    onClick={() => speak(book.description)}
                  >
                    <Volume2 className="h-5 w-5" />
                    Listen
                  </Button>
                  {ttsAllowed && (
                    <Button
                      size="icon"
                      variant="ghost"
                      onClick={stop}
                      aria-label="Stop reading"
                    >
                      <Square className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Content Tabs */}
        <section className="py-8">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex gap-4">
              <AISidebar currentText={book.description} />
              <div className="flex-1">
                <Tabs defaultValue="overview" className="space-y-6">
              <TabsList>
                <TabsTrigger value="overview">Overview</TabsTrigger>
                <TabsTrigger value="ai-summary">AI Summary</TabsTrigger>
                <TabsTrigger value="reviews">Reviews</TabsTrigger>
                <TabsTrigger value="ask-ai">Ask AI</TabsTrigger>
              </TabsList>

              {/* Overview Tab */}
              <TabsContent value="overview" className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle>About this book</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground leading-relaxed">
                      {book.description}
                    </p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>Details</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <dl className="grid gap-4 sm:grid-cols-2">
                      <div>
                        <dt className="text-sm font-medium text-muted-foreground">
                          Author
                        </dt>
                        <dd className="mt-1">{book.author}</dd>
                      </div>
                      <div>
                        <dt className="text-sm font-medium text-muted-foreground">
                          Category
                        </dt>
                        <dd className="mt-1">{book.category}</dd>
                      </div>
                      <div>
                        <dt className="text-sm font-medium text-muted-foreground">
                          Language
                        </dt>
                        <dd className="mt-1">{book.language}</dd>
                      </div>
                      <div>
                        <dt className="text-sm font-medium text-muted-foreground">
                          Published
                        </dt>
                        <dd className="mt-1">{book.publishedYear}</dd>
                      </div>
                      <div>
                        <dt className="text-sm font-medium text-muted-foreground">
                          Pages
                        </dt>
                        <dd className="mt-1">{book.pages}</dd>
                      </div>
                      <div>
                        <dt className="text-sm font-medium text-muted-foreground">
                          Offline Access
                        </dt>
                        <dd className="mt-1">
                          {book.isAvailableOffline ? "Available" : "Not available"}
                        </dd>
                      </div>
                    </dl>
                  </CardContent>
                </Card>
              </TabsContent>

              {/* AI Summary Tab */}
              <TabsContent value="ai-summary" className="space-y-6">
                {summary ? (
                  <AIResponseCard
                    title="AI-Generated Summary"
                    summary={summary}
                    keyPoints={[
                      `Comprehensive coverage of ${book.category.toLowerCase()} topics`,
                      `Written in accessible ${book.language} for students and researchers`,
                      "Includes case studies specific to Ethiopian context",
                      "Recommended for advanced undergraduate and graduate students",
                      "Draws from extensive research and practical experience",
                    ]}
                    sources={[
                      {
                        id: "1",
                        title: book.title,
                        author: book.author,
                        page: 1,
                        relevance: 0.95,
                      },
                      {
                        id: "2",
                        title: "Ethiopian Academic Standards",
                        relevance: 0.82,
                      },
                    ]}
                  />
                ) : (
                  <Card>
                    <CardContent className="py-12">
                      <div className="text-center">
                        <Sparkles className="mx-auto h-12 w-12 text-muted-foreground/50" />
                        <h3 className="mt-4 font-semibold">Generate AI Summary</h3>
                        <p className="mt-2 text-sm text-muted-foreground">
                          Get a quick overview of this book using AI
                        </p>
                        <Button
                          onClick={handleGenerateSummary}
                          disabled={isGeneratingSummary}
                          className="mt-4 gap-2"
                        >
                          {isGeneratingSummary ? (
                            <>
                              <Clock className="h-4 w-4 animate-spin" />
                              Generating...
                            </>
                          ) : (
                            <>
                              <Sparkles className="h-4 w-4" />
                              Generate Summary
                            </>
                          )}
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                )}
              </TabsContent>

              {/* Reviews Tab */}
              <TabsContent value="reviews" className="space-y-6">
                {/* Write Review */}
                <Card>
                  <CardHeader>
                    <CardTitle>Write a Review</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ReviewForm bookId={book.id} onSubmit={handleSubmitReview} />
                  </CardContent>
                </Card>

                {/* Existing Reviews */}
                <Card>
                  <CardHeader>
                    <CardTitle>Reviews ({reviews.length})</CardTitle>
                  </CardHeader>
                  <CardContent>
                    {reviews.length === 0 ? (
                      <p className="text-center text-muted-foreground py-8">
                        No reviews yet. Be the first to review this book!
                      </p>
                    ) : (
                      <div className="space-y-6">
                        {reviews.map((review) => (
                          <div
                            key={review.id}
                            className="border-b border-border pb-6 last:border-0 last:pb-0"
                          >
                            <div className="flex items-start justify-between">
                              <div className="flex items-center gap-3">
                                <Avatar>
                                  <AvatarFallback>
                                    {review.userName
                                      .split(" ")
                                      .map((n) => n[0])
                                      .join("")}
                                  </AvatarFallback>
                                </Avatar>
                                <div>
                                  <p className="font-medium">{review.userName}</p>
                                  <div className="flex items-center gap-2">
                                    <RatingStars rating={review.rating} size="sm" />
                                    <span className="text-xs text-muted-foreground">
                                      {new Date(review.createdAt).toLocaleDateString()}
                                    </span>
                                  </div>
                                </div>
                              </div>
                              <Badge
                                variant={
                                  review.sentiment === "positive"
                                    ? "default"
                                    : review.sentiment === "negative"
                                    ? "destructive"
                                    : "secondary"
                                }
                                className="text-xs"
                              >
                                {review.sentiment}
                              </Badge>
                            </div>
                            <p className="mt-3 text-sm text-muted-foreground">
                              {review.comment}
                            </p>
                          </div>
                        ))}
                      </div>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              {/* Ask AI Tab */}
              <TabsContent value="ask-ai">
                <ChatWindow
                  bookContext={{ id: book.id, title: book.title }}
                  className="h-[600px]"
                />
              </TabsContent>
            </Tabs>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}

